services:
  redis:
    image: 'redis:7.4-alpine'
    container_name: seu-calendario-academico-redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data: null
