services:
  postgres:
    image: postgres:17
    container_name: seu-calendario-academico-db
    environment:
      POSTGRES_DB: seu_calendario_academico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.4-alpine
    container_name: seu-calendario-academico-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
