services:
  app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`api.listadeatividades.davixs.com.br`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=9090"
    expose:
      - "9090"
    depends_on:
      - redis

  redis:
    image: 'redis:7.4-alpine'
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data: null
