-- Seed manual 2026 para banco novo.
-- Idempotente por nome de sala e por par (sala, materia).

BEGIN;

DROP TABLE IF EXISTS seed_2026_salas;
CREATE TEMP TABLE seed_2026_salas (
  nome text,
  semestre text,
  codigo_convite text,
  segredo_lider text
) ON COMMIT DROP;

INSERT INTO seed_2026_salas (nome, semestre, codigo_convite, segredo_lider)
VALUES
  ('ADS 1° Matutino', '1', 'ADS1MAT', 'seu-calendario-2026'),
  ('ADS 2° Matutino', '2', 'ADS2MAT', 'seu-calendario-2026'),
  ('ADS 3° Matutino', '3', 'ADS3MAT', 'seu-calendario-2026'),
  ('ADS 4° Matutino', '4', 'ADS4MAT', 'seu-calendario-2026'),
  ('ADS 5° Matutino', '5', 'ADS5MAT', 'seu-calendario-2026'),
  ('ADS 6° Matutino', '6', 'ADS6MAT', 'seu-calendario-2026'),
  ('ADS 1° Noturno', '1', 'ADS1NOT', 'seu-calendario-2026'),
  ('ADS 2° Noturno', '2', 'ADS2NOT', 'seu-calendario-2026'),
  ('ADS 3° Noturno', '3', 'ADS3NOT', 'seu-calendario-2026'),
  ('ADS 4° Noturno', '4', 'ADS4NOT', 'seu-calendario-2026'),
  ('ADS 5° Noturno', '5', 'ADS5NOT', 'seu-calendario-2026'),
  ('ADS 6° Noturno', '6', 'ADS6NOT', 'seu-calendario-2026'),
  ('DSM 1° Noturno', '1', 'DSM1NOT', 'seu-calendario-2026'),
  ('DSM 2° Noturno', '2', 'DSM2NOT', 'seu-calendario-2026'),
  ('DSM 3° Noturno', '3', 'DSM3NOT', 'seu-calendario-2026'),
  ('DSM 4° Noturno', '4', 'DSM4NOT', 'seu-calendario-2026'),
  ('DSM 5° Noturno', '5', 'DSM5NOT', 'seu-calendario-2026'),
  ('DSM 6° Noturno', '6', 'DSM6NOT', 'seu-calendario-2026'),
  ('GPI 1° Matutino', '1', 'GPI1MAT', 'seu-calendario-2026'),
  ('GPI 2° Matutino', '2', 'GPI2MAT', 'seu-calendario-2026'),
  ('GPI 3° Matutino', '3', 'GPI3MAT', 'seu-calendario-2026'),
  ('GPI 4° Matutino', '4', 'GPI4MAT', 'seu-calendario-2026'),
  ('GPI 5° Matutino', '5', 'GPI5MAT', 'seu-calendario-2026'),
  ('GPI 6° Matutino', '6', 'GPI6MAT', 'seu-calendario-2026'),
  ('GPI 1° Noturno', '1', 'GPI1NOT', 'seu-calendario-2026'),
  ('GPI 2° Noturno', '2', 'GPI2NOT', 'seu-calendario-2026'),
  ('GPI 3° Noturno', '3', 'GPI3NOT', 'seu-calendario-2026'),
  ('GPI 4° Noturno', '4', 'GPI4NOT', 'seu-calendario-2026'),
  ('GPI 5° Noturno', '5', 'GPI5NOT', 'seu-calendario-2026'),
  ('GPI 6° Noturno', '6', 'GPI6NOT', 'seu-calendario-2026'),
  ('GRH 1° Matutino', '1', 'GRH1MAT', 'seu-calendario-2026'),
  ('GRH 2° Matutino', '2', 'GRH2MAT', 'seu-calendario-2026'),
  ('GRH 3° Matutino', '3', 'GRH3MAT', 'seu-calendario-2026'),
  ('GRH 4° Matutino', '4', 'GRH4MAT', 'seu-calendario-2026'),
  ('GRH 5° Matutino', '5', 'GRH5MAT', 'seu-calendario-2026'),
  ('GRH 6° Matutino', '6', 'GRH6MAT', 'seu-calendario-2026'),
  ('GRH 1° Noturno', '1', 'GRH1NOT', 'seu-calendario-2026'),
  ('GRH 2° Noturno', '2', 'GRH2NOT', 'seu-calendario-2026'),
  ('GRH 3° Noturno', '3', 'GRH3NOT', 'seu-calendario-2026'),
  ('GRH 4° Noturno', '4', 'GRH4NOT', 'seu-calendario-2026'),
  ('GRH 5° Noturno', '5', 'GRH5NOT', 'seu-calendario-2026'),
  ('GRH 6° Noturno', '6', 'GRH6NOT', 'seu-calendario-2026');

INSERT INTO sala_de_aula (nome, semestre, codigo_convite, segredo_lider)
SELECT nome, semestre, codigo_convite, segredo_lider
FROM seed_2026_salas ss
WHERE NOT EXISTS (
  SELECT 1 FROM sala_de_aula s WHERE s.nome = ss.nome
)
ON CONFLICT (codigo_convite) DO NOTHING;

UPDATE sala_de_aula s
SET semestre = ss.semestre,
    segredo_lider = ss.segredo_lider
FROM seed_2026_salas ss
WHERE s.nome = ss.nome;

DROP TABLE IF EXISTS seed_2026_materias;
CREATE TEMP TABLE seed_2026_materias (
  sala_nome text,
  nome text,
  professor text
) ON COMMIT DROP;

INSERT INTO seed_2026_materias (sala_nome, nome, professor)
VALUES
  ('ADS 1° Matutino', 'Inglês I', 'Professor'),
  ('ADS 1° Matutino', 'Algoritmos e Lógica de Programação', 'Professor'),
  ('ADS 1° Matutino', 'Engenharia de Software I', 'Professor'),
  ('ADS 1° Matutino', 'Arquitetura e Organização de Computadores', 'Professor'),
  ('ADS 1° Matutino', 'Projeto Integrador I', 'Professor'),
  ('ADS 1° Matutino', 'Comunicação e Expressão', 'Professor'),
  ('ADS 1° Matutino', 'Sistemas Operacionais', 'Professor'),
  ('ADS 2° Matutino', 'Interação Humano Computador', 'Professor'),
  ('ADS 2° Matutino', 'Linguagem de Programação', 'Professor'),
  ('ADS 2° Matutino', 'Gestão Financeira Empresarial com Tecnologia', 'Professor'),
  ('ADS 2° Matutino', 'Cálculo', 'Professor'),
  ('ADS 2° Matutino', 'Engenharia de Software II', 'Professor'),
  ('ADS 2° Matutino', 'Comunicação e Expressão II', 'Professor'),
  ('ADS 2° Matutino', 'Banco de Dados Relacional', 'Professor'),
  ('ADS 2° Matutino', 'Inglês II', 'Professor'),
  ('ADS 3° Matutino', 'Programação Orientada a Objetos', 'Professor'),
  ('ADS 3° Matutino', 'Inglês III', 'Professor'),
  ('ADS 3° Matutino', 'Gestão de Negócios', 'Professor'),
  ('ADS 3° Matutino', 'Laboratório de Banco de Dados', 'Professor'),
  ('ADS 3° Matutino', 'Estrutura de Dados', 'Professor'),
  ('ADS 3° Matutino', 'Experiência do Usuário', 'Professor'),
  ('ADS 3° Matutino', 'Gestão de Projetos Ágeis', 'Professor'),
  ('ADS 4° Matutino', 'Inglês IV', 'Professor'),
  ('ADS 4° Matutino', 'Eletiva I / Programação Web', 'Professor'),
  ('ADS 4° Matutino', 'Programação Orientada a Objetos', 'Professor'),
  ('ADS 4° Matutino', 'Banco de Dados', 'Professor'),
  ('ADS 4° Matutino', 'Engenharia de Software III', 'Professor'),
  ('ADS 4° Matutino', 'Sistemas Operacionais II', 'Professor'),
  ('ADS 4° Matutino', 'Metodologia de Pesquisa Científica e Tecnológica', 'Professor'),
  ('ADS 5° Matutino', 'Redes de Computadores I', 'Professor'),
  ('ADS 5° Matutino', 'Programação Linear', 'Professor'),
  ('ADS 5° Matutino', 'Inglês V', 'Professor'),
  ('ADS 5° Matutino', 'Laboratório de Engenharia de Software', 'Professor'),
  ('ADS 5° Matutino', 'Escolha I / Laboratório de Banco de Dados', 'Professor'),
  ('ADS 5° Matutino', 'Eletiva II / Programação Script', 'Professor'),
  ('ADS 5° Matutino', 'Segurança da Informação', 'Professor'),
  ('ADS 6° Matutino', 'Escolha III / Inteligência Artificial', 'Professor'),
  ('ADS 6° Matutino', 'Empreendedorismo', 'Professor'),
  ('ADS 6° Matutino', 'Escolha II / Tópicos Especiais', 'Professor'),
  ('ADS 6° Matutino', 'Gestão e Governança de TI', 'Professor'),
  ('ADS 6° Matutino', 'Gestão de Equipes', 'Professor'),
  ('ADS 6° Matutino', 'Gestão de Projetos', 'Professor'),
  ('ADS 6° Matutino', 'Ética e Responsabilidade Profissional', 'Professor'),
  ('ADS 6° Matutino', 'Inglês VI', 'Professor'),
  ('ADS 1° Noturno', 'Engenharia de Software', 'Professor'),
  ('ADS 1° Noturno', 'Arquitetura e Organização de Computadores', 'Professor'),
  ('ADS 1° Noturno', 'Algoritmos e Lógica de Programação', 'Professor'),
  ('ADS 1° Noturno', 'Projeto Integrador I', 'Professor'),
  ('ADS 1° Noturno', 'Comunicação e Expressão', 'Professor'),
  ('ADS 1° Noturno', 'Sistemas Operacionais', 'Professor'),
  ('ADS 1° Noturno', 'Inglês I', 'Professor'),
  ('ADS 2° Noturno', 'Banco de Dados Relacional', 'Professor'),
  ('ADS 2° Noturno', 'Inglês II', 'Professor'),
  ('ADS 2° Noturno', 'Engenharia de Software', 'Professor'),
  ('ADS 2° Noturno', 'Interação Humano Computador', 'Professor'),
  ('ADS 2° Noturno', 'Linguagem de Programação', 'Professor'),
  ('ADS 2° Noturno', 'Cálculo', 'Professor'),
  ('ADS 2° Noturno', 'Comunicação e Expressão II', 'Professor'),
  ('ADS 2° Noturno', 'Gestão Financeira Empresarial com Tecnologias', 'Professor'),
  ('ADS 3° Noturno', 'Laboratório de Banco de Dados', 'Professor'),
  ('ADS 3° Noturno', 'Gestão de Negócios', 'Professor'),
  ('ADS 3° Noturno', 'Gestão de Projetos Ágeis', 'Professor'),
  ('ADS 3° Noturno', 'Experiência do Usuário', 'Professor'),
  ('ADS 3° Noturno', 'Inglês III', 'Professor'),
  ('ADS 3° Noturno', 'Programação Orientada a Objetos', 'Professor'),
  ('ADS 3° Noturno', 'Estrutura de Dados', 'Professor'),
  ('ADS 4° Noturno', 'Engenharia de Software III', 'Professor'),
  ('ADS 4° Noturno', 'Inglês IV', 'Professor'),
  ('ADS 4° Noturno', 'Banco de Dados', 'Professor'),
  ('ADS 4° Noturno', 'Programação Orientada a Objetos', 'Professor'),
  ('ADS 4° Noturno', 'Sistemas Operacionais II', 'Professor'),
  ('ADS 4° Noturno', 'Eletiva I / Programação Web', 'Professor'),
  ('ADS 4° Noturno', 'Metodologia de Pesquisa Científica e Tecnológica', 'Professor'),
  ('ADS 5° Noturno', 'Inglês V', 'Professor'),
  ('ADS 5° Noturno', 'Eletiva II / Programação Script', 'Professor'),
  ('ADS 5° Noturno', 'Programação Linear', 'Professor'),
  ('ADS 5° Noturno', 'Segurança da Informação', 'Professor'),
  ('ADS 5° Noturno', 'Laboratório de Engenharia de Software', 'Professor'),
  ('ADS 5° Noturno', 'Escolha I / Laboratório de Banco de Dados', 'Professor'),
  ('ADS 5° Noturno', 'Redes de Computadores I', 'Professor'),
  ('ADS 6° Noturno', 'Escolha II / Inteligência Artificial', 'Professor'),
  ('ADS 6° Noturno', 'Gestão e Governança de TI', 'Professor'),
  ('ADS 6° Noturno', 'Gestão de Projetos', 'Professor'),
  ('ADS 6° Noturno', 'Ética e Responsabilidade Profissional', 'Professor'),
  ('ADS 6° Noturno', 'Inglês VI', 'Professor'),
  ('ADS 6° Noturno', 'Gestão de Projetos (optativa)', 'Professor'),
  ('ADS 6° Noturno', 'Empreendedorismo', 'Professor'),
  ('ADS 6° Noturno', 'Gestão de Equipes', 'Professor'),
  ('ADS 6° Noturno', 'Escolha II / Tópicos Especiais', 'Professor'),
  ('DSM 1° Noturno', 'Desenvolvimento Web I', 'Professor'),
  ('DSM 1° Noturno', 'Engenharia de Software I', 'Professor'),
  ('DSM 1° Noturno', 'Algoritmos e Lógica de Programação', 'Professor'),
  ('DSM 1° Noturno', 'Design Digital', 'Professor'),
  ('DSM 1° Noturno', 'Sistemas Operacionais e Redes', 'Professor'),
  ('DSM 1° Noturno', 'Modelagem de Banco de Dados', 'Professor'),
  ('DSM 2° Noturno', 'Engenharia de Software II', 'Professor'),
  ('DSM 2° Noturno', 'Técnicas de Programação I', 'Professor'),
  ('DSM 2° Noturno', 'Estrutura de Dados', 'Professor'),
  ('DSM 2° Noturno', 'Matemática para Computação', 'Professor'),
  ('DSM 2° Noturno', 'Desenvolvimento Web II', 'Professor'),
  ('DSM 2° Noturno', 'Banco de Dados Relacional', 'Professor'),
  ('DSM 3° Noturno', 'Banco de Dados Não Relacional', 'Professor'),
  ('DSM 3° Noturno', 'Inglês I', 'Professor'),
  ('DSM 3° Noturno', 'Desenvolvimento Web III', 'Professor'),
  ('DSM 3° Noturno', 'Gestão Ágil de Projetos', 'Professor'),
  ('DSM 3° Noturno', 'Interação Humano Computador', 'Professor'),
  ('DSM 3° Noturno', 'Técnicas de Programação II', 'Professor'),
  ('DSM 3° Noturno', 'Álgebra Linear', 'Professor'),
  ('DSM 4° Noturno', 'Programação para Dispositivos Móveis I', 'Professor'),
  ('DSM 4° Noturno', 'Experiência do Usuário', 'Professor'),
  ('DSM 4° Noturno', 'Integração e Entrega', 'Professor'),
  ('DSM 4° Noturno', 'Estatística Aplicada', 'Professor'),
  ('DSM 4° Noturno', 'Inglês II', 'Professor'),
  ('DSM 4° Noturno', 'IoT', 'Professor'),
  ('DSM 4° Noturno', 'Laboratório de Desenvolvimento Web', 'Professor'),
  ('DSM 5° Noturno', 'Redação', 'Professor'),
  ('DSM 5° Noturno', 'Inglês III', 'Professor'),
  ('DSM 5° Noturno', 'Computação em Nuvem I', 'Professor'),
  ('DSM 5° Noturno', 'Aprendizagem de Máquinas', 'Professor'),
  ('DSM 5° Noturno', 'Programação para Dispositivos Móveis II', 'Professor'),
  ('DSM 5° Noturno', 'Segurança no Desenvolvimento de Aplicações', 'Professor'),
  ('DSM 5° Noturno', 'Laboratório de Dispositivos Móveis', 'Professor'),
  ('DSM 6° Noturno', 'Qualidade e Testes de Software', 'Professor'),
  ('DSM 6° Noturno', 'Mineração de Dados', 'Professor'),
  ('DSM 6° Noturno', 'Laboratório de Desenvolvimento Multiplataforma', 'Professor'),
  ('DSM 6° Noturno', 'Processamento de Linguagem Natural', 'Professor'),
  ('DSM 6° Noturno', 'Computação em Nuvem II', 'Professor'),
  ('DSM 6° Noturno', 'Ética Profissional e Patente', 'Professor'),
  ('DSM 6° Noturno', 'Inglês IV', 'Professor'),
  ('GPI 1° Matutino', 'Informática', 'Professor'),
  ('GPI 1° Matutino', 'Comunicação Empresarial', 'Professor'),
  ('GPI 1° Matutino', 'Metodologia de Pesquisa', 'Professor'),
  ('GPI 1° Matutino', 'Tecnologia de Produção', 'Professor'),
  ('GPI 1° Matutino', 'Administração', 'Professor'),
  ('GPI 1° Matutino', 'Inglês I', 'Professor'),
  ('GPI 1° Matutino', 'Cálculo', 'Professor'),
  ('GPI 1° Matutino', 'Informática / Cálculo', 'Professor'),
  ('GPI 1° Matutino', 'Projeto GPI I', 'Professor'),
  ('GPI 2° Matutino', 'Design/Desenho Técnico', 'Professor'),
  ('GPI 2° Matutino', 'Introdução à Contabilidade', 'Professor'),
  ('GPI 2° Matutino', 'Fundamentos de Matemática Financeira', 'Professor'),
  ('GPI 2° Matutino', 'Inglês II', 'Professor'),
  ('GPI 2° Matutino', 'Materiais e Tratamentos', 'Professor'),
  ('GPI 2° Matutino', 'Projeto Integrado GPI / Projeto GPI II', 'Professor'),
  ('GPI 2° Matutino', 'Estatística', 'Professor'),
  ('GPI 2° Matutino', 'Ergonomia', 'Professor'),
  ('GPI 2° Matutino', 'Ergonomia / Economia', 'Professor'),
  ('GPI 3° Matutino', 'Projeto Integrador GPI III', 'Professor'),
  ('GPI 3° Matutino', 'Economia', 'Professor'),
  ('GPI 3° Matutino', 'Design de Produto', 'Professor'),
  ('GPI 3° Matutino', 'Gestão da Produção Aplicada', 'Professor'),
  ('GPI 3° Matutino', 'Custos Industriais', 'Professor'),
  ('GPI 3° Matutino', 'Projeto de Produto I', 'Professor'),
  ('GPI 3° Matutino', 'Inglês III', 'Professor'),
  ('GPI 3° Matutino', 'Estrutura de Operações', 'Professor'),
  ('GPI 3° Matutino', 'Materiais e Ensaios', 'Professor'),
  ('GPI 4° Matutino', 'Projeto de Produto II', 'Professor'),
  ('GPI 4° Matutino', 'PPCP', 'Professor'),
  ('GPI 4° Matutino', 'Gestão da Qualidade', 'Professor'),
  ('GPI 4° Matutino', 'Higiene e Segurança', 'Professor'),
  ('GPI 4° Matutino', 'Inglês IV', 'Professor'),
  ('GPI 4° Matutino', 'Projeto Integrador GPI III/IV', 'Professor'),
  ('GPI 4° Matutino', 'Processo de Produção', 'Professor'),
  ('GPI 4° Matutino', 'Fundamentos de Automação Industrial', 'Professor'),
  ('GPI 5° Matutino', 'Projeto de Fábrica', 'Professor'),
  ('GPI 5° Matutino', 'Projeto de Graduação I', 'Professor'),
  ('GPI 5° Matutino', 'Gestão da Cadeia de Suprimentos', 'Professor'),
  ('GPI 5° Matutino', 'Gestão Ambiental', 'Professor'),
  ('GPI 5° Matutino', 'Fundamentos de Gestão de Projetos', 'Professor'),
  ('GPI 5° Matutino', 'Gestão Financeira', 'Professor'),
  ('GPI 5° Matutino', 'Ética e Direito Empresarial', 'Professor'),
  ('GPI 5° Matutino', 'Espanhol I', 'Professor'),
  ('GPI 6° Matutino', 'Comércio Exterior', 'Professor'),
  ('GPI 6° Matutino', 'Tecnologia da Informação', 'Professor'),
  ('GPI 6° Matutino', 'Gestão de Pessoas', 'Professor'),
  ('GPI 6° Matutino', 'Espanhol II', 'Professor'),
  ('GPI 6° Matutino', 'Marketing', 'Professor'),
  ('GPI 6° Matutino', 'SAP', 'Professor'),
  ('GPI 6° Matutino', 'Projeto de Graduação II', 'Professor'),
  ('GPI 1° Noturno', 'Informática', 'Professor'),
  ('GPI 1° Noturno', 'Metodologia de Pesquisa', 'Professor'),
  ('GPI 1° Noturno', 'Tecnologia de Produção', 'Professor'),
  ('GPI 1° Noturno', 'Fundamentos Comuns Empresariais', 'Professor'),
  ('GPI 1° Noturno', 'Cálculo', 'Professor'),
  ('GPI 1° Noturno', 'Administração', 'Professor'),
  ('GPI 1° Noturno', 'Inglês I', 'Professor'),
  ('GPI 2° Noturno', 'Matemática / Materiais e Tratamento I', 'Professor'),
  ('GPI 2° Noturno', 'Projeto Integrador GPI Local', 'Professor'),
  ('GPI 2° Noturno', 'Estatística', 'Professor'),
  ('GPI 2° Noturno', 'Matemática / Tratamento I', 'Professor'),
  ('GPI 2° Noturno', 'Líder e Empresa / Fundamentos Empresariais', 'Professor'),
  ('GPI 2° Noturno', 'Fundamentos de Matemática Financeira', 'Professor'),
  ('GPI 2° Noturno', 'Introdução à Contabilidade', 'Professor'),
  ('GPI 2° Noturno', 'Ergonomia', 'Professor'),
  ('GPI 2° Noturno', 'Design, Moda e Produto I', 'Professor'),
  ('GPI 2° Noturno', 'Inglês II', 'Professor'),
  ('GPI 3° Noturno', 'Estratégia de Produção e Operações', 'Professor'),
  ('GPI 3° Noturno', 'Projeto Integrador GPI II', 'Professor'),
  ('GPI 3° Noturno', 'Gestão da Produção Aplicada', 'Professor'),
  ('GPI 3° Noturno', 'Economia', 'Professor'),
  ('GPI 3° Noturno', 'Materiais e Tratamentos I', 'Professor'),
  ('GPI 3° Noturno', 'Custos Industriais', 'Professor'),
  ('GPI 3° Noturno', 'Projeto de Produto I', 'Professor'),
  ('GPI 3° Noturno', 'Inglês III', 'Professor'),
  ('GPI 3° Noturno', 'Design, Moda e Produto II', 'Professor'),
  ('GPI 4° Noturno', 'Processo de Produção', 'Professor'),
  ('GPI 4° Noturno', 'Fundamentos de Automação Industrial', 'Professor'),
  ('GPI 4° Noturno', 'Higiene e Segurança do Trabalho', 'Professor'),
  ('GPI 4° Noturno', 'PPCP', 'Professor'),
  ('GPI 4° Noturno', 'Projeto de Produto II', 'Professor'),
  ('GPI 4° Noturno', 'Gestão da Qualidade', 'Professor'),
  ('GPI 4° Noturno', 'Inglês IV', 'Professor'),
  ('GPI 4° Noturno', 'Projeto Integrador GPI III/IV', 'Professor'),
  ('GPI 5° Noturno', 'Espanhol I', 'Professor'),
  ('GPI 5° Noturno', 'Projeto de Graduação I', 'Professor'),
  ('GPI 5° Noturno', 'Gestão Ambiental', 'Professor'),
  ('GPI 5° Noturno', 'Projeto de Fábrica', 'Professor'),
  ('GPI 5° Noturno', 'Fundamentos de Gestão de Projetos', 'Professor'),
  ('GPI 5° Noturno', 'Ética e Direito Empresarial', 'Professor'),
  ('GPI 5° Noturno', 'Gestão Financeira', 'Professor'),
  ('GPI 5° Noturno', 'Gestão da Cadeia de Suprimentos', 'Professor'),
  ('GPI 6° Noturno', 'Projeto de Graduação II', 'Professor'),
  ('GPI 6° Noturno', 'Espanhol II', 'Professor'),
  ('GPI 6° Noturno', 'Tecnologia da Informação', 'Professor'),
  ('GPI 6° Noturno', 'Comércio Exterior', 'Professor'),
  ('GPI 6° Noturno', 'SAP', 'Professor'),
  ('GPI 6° Noturno', 'Marketing e Vendas', 'Professor'),
  ('GPI 6° Noturno', 'Gestão de Pessoas', 'Professor'),
  ('GRH 1° Matutino', 'Inglês I', 'Professor'),
  ('GRH 1° Matutino', 'Projeto Integrador I', 'Professor'),
  ('GRH 1° Matutino', 'Matemática Elementar', 'Professor'),
  ('GRH 1° Matutino', 'Administração Geral', 'Professor'),
  ('GRH 1° Matutino', 'Leitura e Produção de Texto', 'Professor'),
  ('GRH 1° Matutino', 'Comportamento Organizacional', 'Professor'),
  ('GRH 1° Matutino', 'Gestão das Relações Interpessoais', 'Professor'),
  ('GRH 2° Matutino', 'Comunicação Empresarial', 'Professor'),
  ('GRH 2° Matutino', 'Estatística', 'Professor'),
  ('GRH 2° Matutino', 'Gestão de Pessoas na Administração Pública', 'Professor'),
  ('GRH 2° Matutino', 'Projeto Integrador II', 'Professor'),
  ('GRH 2° Matutino', 'Espanhol I', 'Professor'),
  ('GRH 2° Matutino', 'Métodos para Produção do Conhecimento', 'Professor'),
  ('GRH 2° Matutino', 'Captação e Seleção de Talentos', 'Professor'),
  ('GRH 2° Matutino', 'Inglês II', 'Professor'),
  ('GRH 3° Matutino', 'Fundamentos de Economia', 'Professor'),
  ('GRH 3° Matutino', 'Educação Corporativa', 'Professor'),
  ('GRH 3° Matutino', 'Inglês III', 'Professor'),
  ('GRH 3° Matutino', 'Informática Aplicada à Gestão de Pessoas', 'Professor'),
  ('GRH 3° Matutino', 'Projeto Integrador III', 'Professor'),
  ('GRH 3° Matutino', 'Legislação Trabalhista e Previdenciária', 'Professor'),
  ('GRH 3° Matutino', 'Espanhol II', 'Professor'),
  ('GRH 3° Matutino', 'Gestão das Rotinas de Pessoal', 'Professor'),
  ('GRH 4° Matutino', 'Gestão da Inclusão Social', 'Professor'),
  ('GRH 4° Matutino', 'Gestão do Clima Organizacional', 'Professor'),
  ('GRH 4° Matutino', 'Inglês IV', 'Professor'),
  ('GRH 4° Matutino', 'Gestão das Rotinas de Pessoal II', 'Professor'),
  ('GRH 4° Matutino', 'Gestão de Carreiras e Benefícios', 'Professor'),
  ('GRH 4° Matutino', 'Gestão Financeira', 'Professor'),
  ('GRH 4° Matutino', 'Projeto Integrador IV', 'Professor'),
  ('GRH 4° Matutino', 'Informática Aplicada à Gestão de Pessoas II', 'Professor'),
  ('GRH 5° Matutino', 'Inglês V', 'Professor'),
  ('GRH 5° Matutino', 'Saúde e Segurança Ocupacional', 'Professor'),
  ('GRH 5° Matutino', 'Empreendedorismo', 'Professor'),
  ('GRH 5° Matutino', 'Endomarketing', 'Professor'),
  ('GRH 5° Matutino', 'Remuneração Estratégica', 'Professor'),
  ('GRH 5° Matutino', 'Gestão de Conflitos e Negociação', 'Professor'),
  ('GRH 5° Matutino', 'Projeto de Recursos Humanos I', 'Professor'),
  ('GRH 5° Matutino', 'Gestão por Competências', 'Professor'),
  ('GRH 6° Matutino', 'Projeto de Recursos Humanos II', 'Professor'),
  ('GRH 6° Matutino', 'Inglês VI', 'Professor'),
  ('GRH 6° Matutino', 'Gestão do Conhecimento', 'Professor'),
  ('GRH 6° Matutino', 'Auditoria e Gestão da Qualidade de Vida no Trabalho', 'Professor'),
  ('GRH 6° Matutino', 'Consultoria em Gestão de Pessoas', 'Professor'),
  ('GRH 6° Matutino', 'Planejamento Estratégico em RH', 'Professor'),
  ('GRH 6° Matutino', 'Tópicos Especiais em Gestão de Talentos Humanos', 'Professor'),
  ('GRH 6° Matutino', 'Ética e Responsabilidade Social Empresarial', 'Professor'),
  ('GRH 1° Noturno', 'Projeto Integrador I', 'Professor'),
  ('GRH 1° Noturno', 'Leitura e Produção de Textos', 'Professor'),
  ('GRH 1° Noturno', 'Matemática Elementar', 'Professor'),
  ('GRH 1° Noturno', 'Administração Geral', 'Professor'),
  ('GRH 1° Noturno', 'Comportamento Organizacional', 'Professor'),
  ('GRH 1° Noturno', 'Inglês I', 'Professor'),
  ('GRH 1° Noturno', 'Gestão das Relações Interpessoais', 'Professor'),
  ('GRH 2° Noturno', 'Comunicação Empresarial', 'Professor'),
  ('GRH 2° Noturno', 'Métodos para Produção do Conhecimento', 'Professor'),
  ('GRH 2° Noturno', 'Captação e Seleção de Talentos', 'Professor'),
  ('GRH 2° Noturno', 'Gestão de Pessoas na Administração Pública', 'Professor'),
  ('GRH 2° Noturno', 'Projeto Integrador II', 'Professor'),
  ('GRH 2° Noturno', 'Espanhol I', 'Professor'),
  ('GRH 2° Noturno', 'Estatística', 'Professor'),
  ('GRH 2° Noturno', 'Inglês II', 'Professor'),
  ('GRH 3° Noturno', 'Projeto Integrador III', 'Professor'),
  ('GRH 3° Noturno', 'Educação Corporativa', 'Professor'),
  ('GRH 3° Noturno', 'Espanhol II', 'Professor'),
  ('GRH 3° Noturno', 'Gestão das Rotinas de Pessoal', 'Professor'),
  ('GRH 3° Noturno', 'Inglês III', 'Professor'),
  ('GRH 3° Noturno', 'Fundamentos de Economia', 'Professor'),
  ('GRH 3° Noturno', 'Informática Aplicada à Gestão de Pessoas', 'Professor'),
  ('GRH 3° Noturno', 'Legislação Trabalhista e Previdenciária', 'Professor'),
  ('GRH 4° Noturno', 'Gestão da Inclusão Social', 'Professor'),
  ('GRH 4° Noturno', 'Gestão Financeira', 'Professor'),
  ('GRH 4° Noturno', 'Informática Aplicada à Gestão de Pessoas II', 'Professor'),
  ('GRH 4° Noturno', 'Gestão do Clima Organizacional', 'Professor'),
  ('GRH 4° Noturno', 'Gestão de Carreira e Benefícios', 'Professor'),
  ('GRH 4° Noturno', 'Inglês IV', 'Professor'),
  ('GRH 4° Noturno', 'Gestão das Rotinas de Pessoal II', 'Professor'),
  ('GRH 4° Noturno', 'Projeto Integrador IV', 'Professor'),
  ('GRH 5° Noturno', 'Projeto de Recursos Humanos I', 'Professor'),
  ('GRH 5° Noturno', 'Saúde e Segurança Ocupacional', 'Professor'),
  ('GRH 5° Noturno', 'Empreendedorismo', 'Professor'),
  ('GRH 5° Noturno', 'Endomarketing', 'Professor'),
  ('GRH 5° Noturno', 'Inglês V', 'Professor'),
  ('GRH 5° Noturno', 'Gestão de Conflitos e Negociação', 'Professor'),
  ('GRH 5° Noturno', 'Gestão por Competências', 'Professor'),
  ('GRH 5° Noturno', 'Remuneração Estratégica', 'Professor'),
  ('GRH 6° Noturno', 'Projeto de Recursos Humanos II', 'Professor'),
  ('GRH 6° Noturno', 'Planejamento Estratégico em RH', 'Professor'),
  ('GRH 6° Noturno', 'Gestão do Conhecimento', 'Professor'),
  ('GRH 6° Noturno', 'Consultoria em Gestão de Pessoas', 'Professor'),
  ('GRH 6° Noturno', 'Auditoria e Gestão da Qualidade de Vida no Trabalho', 'Professor'),
  ('GRH 6° Noturno', 'Tópicos Especiais em Gestão de Talentos Humanos', 'Professor'),
  ('GRH 6° Noturno', 'Inglês VI', 'Professor'),
  ('GRH 6° Noturno', 'Ética e Responsabilidade Social Empresarial', 'Professor');

INSERT INTO materia (nome, professor, sala_id)
SELECT sm.nome, sm.professor, s.id
FROM seed_2026_materias sm
JOIN sala_de_aula s ON s.nome = sm.sala_nome
WHERE NOT EXISTS (
  SELECT 1
  FROM materia m
  WHERE m.sala_id = s.id
    AND m.nome = sm.nome
);

COMMIT;
