spring.application.name=todolist

# H2 Database (memória para desenvolvimento)
spring.datasource.url=jdbc:h2:mem:todolist_fatec;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Scheduler 12h fixo: 09:00 e 21:00
app.lembrete.cron=0 0 9,21 * * ?
app.lembrete.zone=America/Sao_Paulo

# Resend (env vars)
resend.api-key=${RESEND_API_KEY:}
resend.from=${RESEND_FROM:no-reply@seudominio.com}

# Admin secret (proteção simples)
app.admin.secret=${ADMIN_SECRET:}

# Master Admin (Super Admin global)
app.master-admin.username=${MASTER_ADMIN_USERNAME:davizin99}
app.master-admin.password=${MASTER_ADMIN_PASSWORD:davizin99}
